### ISSUE TITLE
no configuration

### ISSUE THREAD

**Issue by mild-lemon** [mlo821/OctoBuddy#3]
I just installed OctoBuddy, and all I got is an empty config page:
<img width="960" alt="Bildschirmfoto 2021-01-19 um 09 06 04" src="https://user-images.githubusercontent.com/69107300/105005735-fed3ec00-5a35-11eb-97c0-7dba88661271.png">
Maybe there's something br0ken here?

**Comment by GoldenGorilla123** [comment]
On mine, Octobuddy doesn't appear in the plugin list

**Comment by mlo821** [comment]
Hmmmm, @mild-lemon, can you by chance post your log files so I can take a look

**Comment by mlo821** [comment]
Hard to fix without a log :)
