### ISSUE TITLE
Is there a list of functions that this can do somewhere? Or did I miss it?

### ISSUE THREAD

**Issue by CobaltEcho** [mlo821/OctoBuddy#6]
Is there a list of functions that this can do somewhere? Or did I miss it?

**Comment by Hulth** [comment]
https://plugins.octoprint.org/plugins/OctoBuddy/

>OctoBuddy can currently perform the following actions:
> * Home Printer
> * Jog any Axis by a configurable distance
> * Toggle bed temperature between a configurable temperature and 0
> * Toggle nozzle temperature between a configurable temperature and
